fix: update and fix upgraded torusUtils
torusresearch/customauth-swift-sdk pull request #65
Opened 2024-02-16 09:45 UTC by ieow

2024-02-19 03:18 UTC, metalurgical commented on Package.swift
> +        .iOS(.v13), .macOS(.v11)
Why the change in minimum version?

2024-02-19 03:19 UTC, metalurgical submitted a review, later dismissed
CI fails.

2024-02-23 05:17 UTC, metalurgical approved these changes

2024-03-07 03:57 UTC, himanshuchawla009 requested changes

2024-03-07 03:57 UTC, himanshuchawla009 commented on Sources/CustomAuth/CustomAuth.swift
> +    public init(web3AuthClientId: String = "", aggregateVerifierType: verifierTypes, aggregateVerifier: String, subVerifierDetails: [SubVerifierDetails], network: TorusNetwork = .legacy(.MAINNET), lo
web3AuthClientId should be mandatory

2024-03-07 03:57 UTC, himanshuchawla009 commented on Sources/CustomAuth/CustomAuth.swift
> +    public init(web3AuthClientId: String = "", aggregateVerifierType: verifierTypes, aggregateVerifier: String, subVerifierDetails: [SubVerifierDetails], network: TorusNetwork = .legacy(.MAINNET), lo
we can make init params same as web sdk constructor

2024-03-07 03:57 UTC, himanshuchawla009 commented on Sources/CustomAuth/CustomAuth.swift
> +    public init(web3AuthClientId: String = "", aggregateVerifierType: verifierTypes, aggregateVerifier: String, subVerifierDetails: [SubVerifierDetails], network: TorusNetwork = .legacy(.MAINNET), lo
https://github.com/torusresearch/CustomAuth/blob/master/src/login.ts

2024-03-07 03:57 UTC, himanshuchawla009 commented on Sources/CustomAuth/Extension/EthereumNetworkFND+extension.swift
> +                return "\(path)"
replace custom with default case and return "https://signer.tor.us" in case of default

2024-03-08 03:37 UTC, ieow commented on Sources/CustomAuth/CustomAuth.swift
> +    public init(web3AuthClientId: String = "", aggregateVerifierType: verifierTypes, aggregateVerifier: String, subVerifierDetails: [SubVerifierDetails], network: TorusNetwork = .legacy(.MAINNET), lo
made web3AuthClientId and network mandatory

2024-03-08 03:40 UTC, metalurgical approved these changes
lgtm

2024-03-12 05:54 UTC, metalurgical commented
Updated in #67

2024-03-12 05:54 UTC, closed without merging