Re-align CustomAuth
torusresearch/customauth-swift-sdk pull request #75
Opened 2024-06-12 07:44 UTC by metalurgical

This PR seeks to re-align the current implementation of custom-auth-swift to that of the web implementation of CustomAuth.

This will reduce the overhead of differences a developer would need to remember between the two and provide an overall better experience.

This will also provide better long term maintainability and make feature parity simpler to implement between the two.

Note this is a breaking change and needs to be released as a major version.

ToDo:
    Comprehensive testing
    Update customAuthDemo

2024-09-04 08:50 UTC, himanshuchawla009 requested changes

2024-09-04 08:50 UTC, himanshuchawla009 commented on Sources/CustomAuth/Common/VerifierResponses/TorusVerifierResponses.swift
> +    public let extraVerifierParams: PassKeyExtraParams?
why name of param is PassKeyExtraParams? It should be generic right?

2024-09-04 08:50 UTC, himanshuchawla009 commented on Sources/CustomAuth/Handlers/Protocol/AbstractLoginHandler.swift
> +        nonce = try SecretKey().serialize().addLeading0sForLength64()
it doesnt have to be of length 64, as its just a random string not a cryptographic key

2024-09-04 08:50 UTC, himanshuchawla009 commented on Sources/CustomAuth/Helpers/Common.swift
> +        case .google: return sub
i think we need to add caseSenstive call for sub and name as well similar to web sdks

2024-09-04 08:50 UTC, himanshuchawla009 commented on Sources/CustomAuth/CustomAuthArgs.swift
> +    public init(urlScheme: String, metadataUrl: String? = nil, network: TorusNetwork, enableLogging: Bool = false, enableOneKey: Bool, apiKey: String? = nil, popupFeatures: String? = nil, storageServ
we need to make sure the default values of args is same as web sdk , for ex currently legacyMetadataHost is not in in web

```
web params
 constructor({
    baseUrl,
    network,
    enableLogging = false,
    redirectToOpener = false,
    redirectPathName = "redirect",
    apiKey = "torus-default",
    uxMode = UX_MODE.POPUP,
    locationReplaceOnRedirect = false,
    popupFeatures,
    storageServerUrl = "https://session.web3auth.io",
    sentry,
    enableOneKey = false,
    web3AuthClientId,
    useDkg,
    metadataUrl = "https://metadata.tor.us",
    keyType = "secp256k1",
    serverTimeOffset = 0,
    
    ```

2024-09-04 08:50 UTC, himanshuchawla009 commented on Sources/CustomAuth/CustomAuth.swift
> +        let torusKey = try await getTorusKey(verifier: userInfo.verifier, verifierParams: verifyParams, idToken: loginParams.idToken!)
we should also pass extra params in getTorusKey function as being done in web sdk

2024-09-04 08:50 UTC, himanshuchawla009 commented on Sources/CustomAuth/CustomAuth.swift
> +        let aggregateTorusKey = try await getTorusKey(verifier: args.aggregateLoginParams.verifierIdentifier, verifierParams: aggregateParams, idToken: String(data: aggregateIdToken, encoding: .utf8)
same as above, extra params should be passed

2024-09-04 08:55 UTC, metalurgical commented on Sources/CustomAuth/Helpers/Common.swift
> +        case .google: return sub
Good catch, thanks will fix.

2024-09-04 09:01 UTC, metalurgical commented on Sources/CustomAuth/CustomAuthArgs.swift
> +    public init(urlScheme: String, metadataUrl: String? = nil, network: TorusNetwork, enableLogging: Bool = false, enableOneKey: Bool, apiKey: String? = nil, popupFeatures: String? = nil, storageServ
I will double check these. 

Some of them don't make sense, for example uxMode and Keytype.

UxMode: It will go to an external browser and then have to redirect back to the application from the browser. How Apple has done `aswebauthenticationsession`.
keyType: Only secp256k1 is currently supported, we still need to add ed25519 support to mobile.

2024-09-04 09:02 UTC, metalurgical commented on Sources/CustomAuth/Common/VerifierResponses/TorusVerifierResponses.swift
> +    public let extraVerifierParams: PassKeyExtraParams?
There was a reason for this type, will go find the explanation again.

2024-09-04 09:59 UTC, himanshuchawla009 commented on Sources/CustomAuth/CustomAuthArgs.swift
> +    public init(urlScheme: String, metadataUrl: String? = nil, network: TorusNetwork, enableLogging: Bool = false, enableOneKey: Bool, apiKey: String? = nil, popupFeatures: String? = nil, storageServ
yupp we dont have to support all but make sure existing one's have same default values

2024-09-04 22:19 UTC, metalurgical commented on Sources/CustomAuth/Common/VerifierResponses/TorusVerifierResponses.swift
> +    public let extraVerifierParams: PassKeyExtraParams?
https://github.com/torusresearch/CustomAuth/blob/00de81e24a27dbc53ab9fbc2f4c6ae9891a96ee6/src/handlers/interfaces.ts#L28

2024-09-04 23:00 UTC, metalurgical commented on Sources/CustomAuth/CustomAuth.swift
> +        let torusKey = try await getTorusKey(verifier: userInfo.verifier, verifierParams: verifyParams, idToken: loginParams.idToken!)
This as far as I can tell is PassKeys related, which is not included here as more information is needed to implement it.

Have extended the signatures so long to support this.

In torus.js we strongly typed the extraParams (which we propagated to the mobile sdks as well):
https://github.com/torusresearch/torus.js/blob/f61bf06e27c8fd3885ed12e78a637550298193e1/src/TorusUtilsExtraParams.ts#L4

However it seems CustomAuth needs an update (or might have already since this PR) for this since there is no viable conversion for this (some info will be lost):
```
PassKeyExtraParams -> ExtraParams -> TorusUtilsExtraParams
```
https://github.com/torusresearch/torus.js/blob/f61bf06e27c8fd3885ed12e78a637550298193e1/src/TorusUtilsExtraParams.ts#L4
https://github.com/torusresearch/CustomAuth/blob/00de81e24a27dbc53ab9fbc2f4c6ae9891a96ee6/src/handlers/interfaces.ts#L24
https://github.com/torusresearch/CustomAuth/blob/00de81e24a27dbc53ab9fbc2f4c6ae9891a96ee6/src/handlers/interfaces.ts#L28

2024-09-05 00:10 UTC, metalurgical commented on Sources/CustomAuth/Handlers/Protocol/AbstractLoginHandler.swift
> +        nonce = try SecretKey().serialize().addLeading0sForLength64()
This will still be a random string, not so?

2024-09-05 00:10 UTC, metalurgical commented on Sources/CustomAuth/Helpers/Common.swift
> +        case .google: return sub
Have checked this, did discover there is a missing handler, have added a todo for now.

2024-09-05 00:11 UTC, metalurgical commented on Sources/CustomAuth/CustomAuthArgs.swift
> +    public init(urlScheme: String, metadataUrl: String? = nil, network: TorusNetwork, enableLogging: Bool = false, enableOneKey: Bool, apiKey: String? = nil, popupFeatures: String? = nil, storageServ
Have added the defaults.

2024-09-05 07:51 UTC, metalurgical commented on Sources/CustomAuth/CustomAuth.swift
> +        let torusKey = try await getTorusKey(verifier: userInfo.verifier, verifierParams: verifyParams, idToken: loginParams.idToken!)
As discussed, removed `PasskeysExtraParams` for now.

2024-09-09 02:46 UTC, metalurgical commented
Comments have been resolved. I think more than once review and approval on this PR is very necessary.

2024-09-09 05:35 UTC, chaitanyapotti commented on Sources/CustomAuth/Handlers/HandlerFactory.swift
> +            return try RedditLoginHandler(clientId: params.clientId, verifier: params.verifier, urlScheme: params.urlScheme, redirectURL: params.redirectURL, typeOfLogin: params.typeOfLogin, jwtParam
reddit should be jwt handler. pls deprecate redditLoginHandler

2024-09-09 07:49 UTC, shahbaz17 commented on Sources/CustomAuth/CustomAuth.swift
> +    public func triggerHybridAggregateLogin(args: HybridAggregateLoginParams) async throws -> TorusHybridAggregateLoginResponse {
What about this one @chaitanyapotti?

2024-09-10 03:04 UTC, metalurgical commented on Sources/CustomAuth/CustomAuth.swift
> +    public func triggerHybridAggregateLogin(args: HybridAggregateLoginParams) async throws -> TorusHybridAggregateLoginResponse {
Removed.

2024-09-30 20:58 UTC, metalurgical commented
Close #32 
Close #51 
Close #74 

Resolve #7 
Resolve #8 
Resolve #10 
Resolve #12 
Resolve #18 
Resolve #52 
Resolve #66 
Close #7 
Close #8 
Close #10 
Close #12 
Close #18 
Close #52 
Close #66

2024-10-09 04:22 UTC, himanshuchawla009 submitted a review, later dismissed

2024-10-09 04:22 UTC, himanshuchawla009 commented on Sources/CustomAuth/Handlers/HandlerFactory.swift
> +            throw CASDKError.invalidAuth0Options
i think we should comment out .passwordless if we dont support it yet so that it will throw correct error msg

2024-10-09 04:25 UTC, metalurgical commented on Sources/CustomAuth/Handlers/HandlerFactory.swift
> +            throw CASDKError.invalidAuth0Options
Passwordless is supported, just not this option, since there isn't a test configuration for this to be found.

Will change the error that that is thrown here.

2024-10-09 04:28 UTC, metalurgical commented on Sources/CustomAuth/Handlers/HandlerFactory.swift
> +            throw CASDKError.invalidAuth0Options
Updated

2024-10-09 04:31 UTC, himanshuchawla009 approved these changes
lgtm

2024-10-24 08:28 UTC, merged